### ISSUE TITLE
Dependabot vs tfupdate

### ISSUE THREAD

**Issue by MPV** [minamijoyo/tfupdate#30]
How do they compare? 

I'm using `tfupdate` today and I've found that it works well. 

I noticed you've been trying out Dependabot for similar (same?) use cases here:

https://github.com/minamijoyo/dependabot-terraform-test

Are there still reasons not to use Dependabot over tfupdate (feature-wise)?

**Comment by minamijoyo** [comment]
At the time of writing, dependabot has not support HCL2, that is to say, it doesn't work with Terraform v0.12 or later. It seems to be unmaintained for now.
https://github.com/dependabot/dependabot-core/issues/1176

To be fair, If you are looking for a SaaS solution, another option is renovate. Since I've not use renovate so I don't know the exact difference in features.
https://docs.renovatebot.com/modules/manager/terraform/

The tfupdate itself is just a CLI tool, it allows you to fully control an entire workflow by yourself. Which one you prefer is up to you.

**Comment by MPV** [comment]
@minamijoyo Thanks for sharing your insights. 🥰

Seems like we have made the right choice in trying out `tfupdate`. 🎉

**Comment by minamijoyo** [comment]
Since then, the dependabot finally supports Terraform v1.0 and HCL2. The tfupdate gives you ways to build your own CI pipeline, but it is not purely a replacement for dependabot. Use whichever you prefer. Thanks!
